name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  entity:
    path: ../entity

  flutter_riverpod: ^2.4.5
  riverpod_lint: ^2.3.7

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
